# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: 'sdk'
      version: '5.0.100'
  - script: dotnet build ./src2/MIXERP.sln
    displayName: 'dotnet build'
  - task: DotNetCoreCLI@2
    displayName: 'run tests'
    inputs:
      command: test
      arguments:  '--logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude=[xunit.*]*%2c[System.*]*'
      projects: 'tests/**/*.csproj'
      nobuild: true
  
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml  

- job: macOS
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: 'sdk'
      version: '5.0.100'
  - script: dotnet build ./src2/MIXERP.sln
    displayName: 'dotnet build'
  - task: DotNetCoreCLI@2
    displayName: 'run tests'
    inputs:
      command: test
      arguments:  '--logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude=[xunit.*]*%2c[System.*]*'
      projects: 'tests/**/*.csproj'
      nobuild: true
  
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml  

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: 'sdk'
      version: '5.0.100'
  - task: DotNetCoreCLI@2
    displayName: 'Restoring code using dotnet restore'
    inputs: 
      command: 'restore'
      projects: '**/*/*.csproj'
      includeNuGetOrg: true
  - script: dotnet build ./src2/MIXERP.sln
    displayName: 'dotnet build'
  - task: DotNetCoreCLI@2
    displayName: 'run tests'
    inputs:
      command: test
      arguments:  '--logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude=[xunit.*]*%2c[System.*]*'
      projects: 'tests/**/*.csproj'
      nobuild: true
  
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml  
#########################
##- job: LinuxRelease
##  pool:
##    vmImage: 'ubuntu-18.04'
##  variables:
##    buildConfiguration: 'Release'
##  steps:
##  - task: UseDotNet@2
##    displayName: 'Use .NET Core sdk'
##    inputs:
##      packageType: 'sdk'
##      version: '5.0.100'
##  - script: dotnet build ./src2/MIXERP.Net5.sln
##    displayName: 'dotnet build $(./src2/MIXERP.Net5.sln)'
##  - task: DotNetCoreCLI@2
##    displayName: 'run tests'
##    inputs:
##      command: test
##      arguments:  '--configuration $(buildConfiguration) --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Exclude=[xunit.*]*%2c[System.*]*'
##      projects: 'tests/**/*.csproj'
##      nobuild: true
     
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(Build.SourcesDirectory)/coverlet/reports/Cobertura.xml  
